[package]
name = "emacs-rs-module"
version = "0.2.0"
authors = ["Nguyễn Tuấn Anh <ubolonton@gmail.com>"]
description = "An Emacs dynamic module that helps developing other dynamic modules, in Rust"
license = "BSD-3-Clause"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.34"
libloading = "0.4.3"
lazy_static = "1.0.0"
emacs = { path = "..", version = "0.2.0" }
